### ISSUE TITLE
公开信全文链接打不开啦

### ISSUE THREAD

**Issue by Trini7** [xokctah/996.petition#2]
（公开信全文见：http://t.cn/E6cPHzT）

**Comment by simon300000** [comment]
不知道你在哪里看到这个链接的，但是这个链接把后面的`）`也包括进去了，所以是404
正确的链接应该是http://t.cn/E6cPHzT

或者：
（公开信全文见：http://t.cn/E6cPHzT ）

**Comment by Trini7** [comment]
> 不知道你在哪里看到这个链接的，但是这个链接把后面的`）`也包括进去了，所以是404
> 正确的链接应该是http://t.cn/E6cPHzT
> 
> 或者：
> （公开信全文见：http://t.cn/E6cPHzT ）

= =我的问题

**Comment by Trini7** [comment]
> 不知道你在哪里看到这个链接的，但是这个链接把后面的`）`也包括进去了，所以是404
> 正确的链接应该是http://t.cn/E6cPHzT
> 
> 或者：
> （公开信全文见：http://t.cn/E6cPHzT ）

![image](https://user-images.githubusercontent.com/12758600/55712618-a9c21400-5a21-11e9-958a-d75ccd4b1c45.png)

建议截图处 加个空格？  不然就出现我这样的问题了。

**Comment by simon300000** [comment]
发了个pr #3 应该能修复你所说的问题→_→
